### ISSUE TITLE
Food can spawn in snake

### ISSUE THREAD

**Issue by jwilm** [jvns/snake.rs#1]
This is really awesome, and I spent more time playing it than I care to admit :laughing: 

Found a little bug though--food can spawn in the snake:

![image](https://cloud.githubusercontent.com/assets/4285147/25114992/b14b6c0a-23b7-11e7-891c-3611f45b5bbb.png)

**Comment by jvns** [comment]
thanks for the report! (and i am impressed by how long you played for :) :) . should be fixed now!
